# typed: strong
# This is an autogenerated file for Rails helpers.
# Please rerun rake rails_rbi:mailers to regenerate.
class Ektar::ApplicationMailer
  sig { returns(ActionMailer::MessageDelivery) }
  def self.url_options; end
end
