# typed: strong
# This is an autogenerated file for Rails helpers.
# Please rerun rake rails_rbi:mailers to regenerate.
class Ektar::InvitationMailer
  sig { returns(ActionMailer::MessageDelivery) }
  def self.invite; end
end
