# typed: strong
# This is an autogenerated file for Rails routes.
# Please run rake rails_rbi:routes to regenerate.
class ActionController::Base
  include GeneratedUrlHelpers
end

module ActionView::Helpers
  include GeneratedUrlHelpers
end

class ActionMailer::Base
  include GeneratedUrlHelpers
end

module GeneratedUrlHelpers
  # Sigs for route /ektar
  sig { params(args: T.untyped, kwargs: T.untyped).returns(String) }
  def ektar_path(*args, **kwargs); end

  sig { params(args: T.untyped, kwargs: T.untyped).returns(String) }
  def ektar_url(*args, **kwargs); end

  # Sigs for route /rails/action_mailbox/postmark/inbound_emails(.:format)
  sig { params(args: T.untyped, kwargs: T.untyped).returns(String) }
  def rails_postmark_inbound_emails_path(*args, **kwargs); end

  sig { params(args: T.untyped, kwargs: T.untyped).returns(String) }
  def rails_postmark_inbound_emails_url(*args, **kwargs); end

  # Sigs for route /rails/action_mailbox/relay/inbound_emails(.:format)
  sig { params(args: T.untyped, kwargs: T.untyped).returns(String) }
  def rails_relay_inbound_emails_path(*args, **kwargs); end

  sig { params(args: T.untyped, kwargs: T.untyped).returns(String) }
  def rails_relay_inbound_emails_url(*args, **kwargs); end

  # Sigs for route /rails/action_mailbox/sendgrid/inbound_emails(.:format)
  sig { params(args: T.untyped, kwargs: T.untyped).returns(String) }
  def rails_sendgrid_inbound_emails_path(*args, **kwargs); end

  sig { params(args: T.untyped, kwargs: T.untyped).returns(String) }
  def rails_sendgrid_inbound_emails_url(*args, **kwargs); end

  # Sigs for route /rails/action_mailbox/mandrill/inbound_emails(.:format)
  sig { params(args: T.untyped, kwargs: T.untyped).returns(String) }
  def rails_mandrill_inbound_health_check_path(*args, **kwargs); end

  sig { params(args: T.untyped, kwargs: T.untyped).returns(String) }
  def rails_mandrill_inbound_health_check_url(*args, **kwargs); end

  # Sigs for route /rails/action_mailbox/mandrill/inbound_emails(.:format)
  sig { params(args: T.untyped, kwargs: T.untyped).returns(String) }
  def rails_mandrill_inbound_emails_path(*args, **kwargs); end

  sig { params(args: T.untyped, kwargs: T.untyped).returns(String) }
  def rails_mandrill_inbound_emails_url(*args, **kwargs); end

  # Sigs for route /rails/action_mailbox/mailgun/inbound_emails/mime(.:format)
  sig { params(args: T.untyped, kwargs: T.untyped).returns(String) }
  def rails_mailgun_inbound_emails_path(*args, **kwargs); end

  sig { params(args: T.untyped, kwargs: T.untyped).returns(String) }
  def rails_mailgun_inbound_emails_url(*args, **kwargs); end

  # Sigs for route /rails/conductor/action_mailbox/inbound_emails(.:format)
  sig { params(args: T.untyped, kwargs: T.untyped).returns(String) }
  def rails_conductor_inbound_emails_path(*args, **kwargs); end

  sig { params(args: T.untyped, kwargs: T.untyped).returns(String) }
  def rails_conductor_inbound_emails_url(*args, **kwargs); end

  # Sigs for route /rails/conductor/action_mailbox/inbound_emails/new(.:format)
  sig { params(args: T.untyped, kwargs: T.untyped).returns(String) }
  def new_rails_conductor_inbound_email_path(*args, **kwargs); end

  sig { params(args: T.untyped, kwargs: T.untyped).returns(String) }
  def new_rails_conductor_inbound_email_url(*args, **kwargs); end

  # Sigs for route /rails/conductor/action_mailbox/inbound_emails/:id/edit(.:format)
  sig { params(args: T.untyped, kwargs: T.untyped).returns(String) }
  def edit_rails_conductor_inbound_email_path(*args, **kwargs); end

  sig { params(args: T.untyped, kwargs: T.untyped).returns(String) }
  def edit_rails_conductor_inbound_email_url(*args, **kwargs); end

  # Sigs for route /rails/conductor/action_mailbox/inbound_emails/:id(.:format)
  sig { params(args: T.untyped, kwargs: T.untyped).returns(String) }
  def rails_conductor_inbound_email_path(*args, **kwargs); end

  sig { params(args: T.untyped, kwargs: T.untyped).returns(String) }
  def rails_conductor_inbound_email_url(*args, **kwargs); end

  # Sigs for route /rails/conductor/action_mailbox/:inbound_email_id/reroute(.:format)
  sig { params(args: T.untyped, kwargs: T.untyped).returns(String) }
  def rails_conductor_inbound_email_reroute_path(*args, **kwargs); end

  sig { params(args: T.untyped, kwargs: T.untyped).returns(String) }
  def rails_conductor_inbound_email_reroute_url(*args, **kwargs); end

  # Sigs for route /rails/active_storage/blobs/:signed_id/*filename(.:format)
  sig { params(args: T.untyped, kwargs: T.untyped).returns(String) }
  def rails_service_blob_path(*args, **kwargs); end

  sig { params(args: T.untyped, kwargs: T.untyped).returns(String) }
  def rails_service_blob_url(*args, **kwargs); end

  # Sigs for route /rails/active_storage/representations/:signed_blob_id/:variation_key/*filename(.:format)
  sig { params(args: T.untyped, kwargs: T.untyped).returns(String) }
  def rails_blob_representation_path(*args, **kwargs); end

  sig { params(args: T.untyped, kwargs: T.untyped).returns(String) }
  def rails_blob_representation_url(*args, **kwargs); end

  # Sigs for route /rails/active_storage/disk/:encoded_key/*filename(.:format)
  sig { params(args: T.untyped, kwargs: T.untyped).returns(String) }
  def rails_disk_service_path(*args, **kwargs); end

  sig { params(args: T.untyped, kwargs: T.untyped).returns(String) }
  def rails_disk_service_url(*args, **kwargs); end

  # Sigs for route /rails/active_storage/disk/:encoded_token(.:format)
  sig { params(args: T.untyped, kwargs: T.untyped).returns(String) }
  def update_rails_disk_service_path(*args, **kwargs); end

  sig { params(args: T.untyped, kwargs: T.untyped).returns(String) }
  def update_rails_disk_service_url(*args, **kwargs); end

  # Sigs for route /rails/active_storage/direct_uploads(.:format)
  sig { params(args: T.untyped, kwargs: T.untyped).returns(String) }
  def rails_direct_uploads_path(*args, **kwargs); end

  sig { params(args: T.untyped, kwargs: T.untyped).returns(String) }
  def rails_direct_uploads_url(*args, **kwargs); end
end

module GeneratedUrlHelpers
  # Sigs for route /
  sig { params(args: T.untyped, kwargs: T.untyped).returns(String) }
  def root_path(*args, **kwargs); end

  sig { params(args: T.untyped, kwargs: T.untyped).returns(String) }
  def root_url(*args, **kwargs); end

  # Sigs for route /sesion/new(.:format)
  sig { params(args: T.untyped, kwargs: T.untyped).returns(String) }
  def new_sessions_path(*args, **kwargs); end

  sig { params(args: T.untyped, kwargs: T.untyped).returns(String) }
  def new_sessions_url(*args, **kwargs); end

  # Sigs for route /sesion(.:format)
  sig { params(args: T.untyped, kwargs: T.untyped).returns(String) }
  def sessions_path(*args, **kwargs); end

  sig { params(args: T.untyped, kwargs: T.untyped).returns(String) }
  def sessions_url(*args, **kwargs); end

  # Sigs for route /registro(.:format)
  sig { params(args: T.untyped, kwargs: T.untyped).returns(String) }
  def registrations_path(*args, **kwargs); end

  sig { params(args: T.untyped, kwargs: T.untyped).returns(String) }
  def registrations_url(*args, **kwargs); end

  # Sigs for route /registro/new(.:format)
  sig { params(args: T.untyped, kwargs: T.untyped).returns(String) }
  def new_registration_path(*args, **kwargs); end

  sig { params(args: T.untyped, kwargs: T.untyped).returns(String) }
  def new_registration_url(*args, **kwargs); end

  # Sigs for route /cambiar_contrasena(.:format)
  sig { params(args: T.untyped, kwargs: T.untyped).returns(String) }
  def reset_password_index_path(*args, **kwargs); end

  sig { params(args: T.untyped, kwargs: T.untyped).returns(String) }
  def reset_password_index_url(*args, **kwargs); end

  # Sigs for route /cambiar_contrasena/new(.:format)
  sig { params(args: T.untyped, kwargs: T.untyped).returns(String) }
  def new_reset_password_path(*args, **kwargs); end

  sig { params(args: T.untyped, kwargs: T.untyped).returns(String) }
  def new_reset_password_url(*args, **kwargs); end

  # Sigs for route /seleccionar_organizacion(.:format)
  sig { params(args: T.untyped, kwargs: T.untyped).returns(String) }
  def select_organization_index_path(*args, **kwargs); end

  sig { params(args: T.untyped, kwargs: T.untyped).returns(String) }
  def select_organization_index_url(*args, **kwargs); end

  # Sigs for route /seleccionar_organizacion/new(.:format)
  sig { params(args: T.untyped, kwargs: T.untyped).returns(String) }
  def new_select_organization_path(*args, **kwargs); end

  sig { params(args: T.untyped, kwargs: T.untyped).returns(String) }
  def new_select_organization_url(*args, **kwargs); end

  # Sigs for route /seleccionar_organizacion/:id(.:format)
  sig { params(args: T.untyped, kwargs: T.untyped).returns(String) }
  def select_organization_path(*args, **kwargs); end

  sig { params(args: T.untyped, kwargs: T.untyped).returns(String) }
  def select_organization_url(*args, **kwargs); end

  # Sigs for route /contrasena(.:format)
  sig { params(args: T.untyped, kwargs: T.untyped).returns(String) }
  def edit_passwords_path(*args, **kwargs); end

  sig { params(args: T.untyped, kwargs: T.untyped).returns(String) }
  def edit_passwords_url(*args, **kwargs); end

  # Sigs for route /contrasena(.:format)
  sig { params(args: T.untyped, kwargs: T.untyped).returns(String) }
  def passwords_path(*args, **kwargs); end

  sig { params(args: T.untyped, kwargs: T.untyped).returns(String) }
  def passwords_url(*args, **kwargs); end

  # Sigs for route /registro(.:format)
  sig { params(args: T.untyped, kwargs: T.untyped).returns(String) }
  def new_registrations_path(*args, **kwargs); end

  sig { params(args: T.untyped, kwargs: T.untyped).returns(String) }
  def new_registrations_url(*args, **kwargs); end

  # Sigs for route /invitacion(/:token)(.:format)
  sig { params(args: T.untyped, kwargs: T.untyped).returns(String) }
  def accept_invitations_path(*args, **kwargs); end

  sig { params(args: T.untyped, kwargs: T.untyped).returns(String) }
  def accept_invitations_url(*args, **kwargs); end

  # Sigs for route /super_admin(.:format)
  sig { params(args: T.untyped, kwargs: T.untyped).returns(String) }
  def super_admin_root_path(*args, **kwargs); end

  sig { params(args: T.untyped, kwargs: T.untyped).returns(String) }
  def super_admin_root_url(*args, **kwargs); end

  # Sigs for route /super_admin/organizaciones(.:format)
  sig { params(args: T.untyped, kwargs: T.untyped).returns(String) }
  def super_admin_organizations_path(*args, **kwargs); end

  sig { params(args: T.untyped, kwargs: T.untyped).returns(String) }
  def super_admin_organizations_url(*args, **kwargs); end

  # Sigs for route /super_admin/organizaciones/new(.:format)
  sig { params(args: T.untyped, kwargs: T.untyped).returns(String) }
  def new_super_admin_organization_path(*args, **kwargs); end

  sig { params(args: T.untyped, kwargs: T.untyped).returns(String) }
  def new_super_admin_organization_url(*args, **kwargs); end

  # Sigs for route /super_admin/organizaciones/:id/edit(.:format)
  sig { params(args: T.untyped, kwargs: T.untyped).returns(String) }
  def edit_super_admin_organization_path(*args, **kwargs); end

  sig { params(args: T.untyped, kwargs: T.untyped).returns(String) }
  def edit_super_admin_organization_url(*args, **kwargs); end

  # Sigs for route /super_admin/organizaciones/:id(.:format)
  sig { params(args: T.untyped, kwargs: T.untyped).returns(String) }
  def super_admin_organization_path(*args, **kwargs); end

  sig { params(args: T.untyped, kwargs: T.untyped).returns(String) }
  def super_admin_organization_url(*args, **kwargs); end

  # Sigs for route /super_admin/planes(.:format)
  sig { params(args: T.untyped, kwargs: T.untyped).returns(String) }
  def super_admin_plans_path(*args, **kwargs); end

  sig { params(args: T.untyped, kwargs: T.untyped).returns(String) }
  def super_admin_plans_url(*args, **kwargs); end

  # Sigs for route /super_admin/planes/new(.:format)
  sig { params(args: T.untyped, kwargs: T.untyped).returns(String) }
  def new_super_admin_plan_path(*args, **kwargs); end

  sig { params(args: T.untyped, kwargs: T.untyped).returns(String) }
  def new_super_admin_plan_url(*args, **kwargs); end

  # Sigs for route /super_admin/planes/:id/edit(.:format)
  sig { params(args: T.untyped, kwargs: T.untyped).returns(String) }
  def edit_super_admin_plan_path(*args, **kwargs); end

  sig { params(args: T.untyped, kwargs: T.untyped).returns(String) }
  def edit_super_admin_plan_url(*args, **kwargs); end

  # Sigs for route /super_admin/planes/:id(.:format)
  sig { params(args: T.untyped, kwargs: T.untyped).returns(String) }
  def super_admin_plan_path(*args, **kwargs); end

  sig { params(args: T.untyped, kwargs: T.untyped).returns(String) }
  def super_admin_plan_url(*args, **kwargs); end

  # Sigs for route /super_admin/usuarios(.:format)
  sig { params(args: T.untyped, kwargs: T.untyped).returns(String) }
  def super_admin_users_path(*args, **kwargs); end

  sig { params(args: T.untyped, kwargs: T.untyped).returns(String) }
  def super_admin_users_url(*args, **kwargs); end

  # Sigs for route /super_admin/usuarios/new(.:format)
  sig { params(args: T.untyped, kwargs: T.untyped).returns(String) }
  def new_super_admin_user_path(*args, **kwargs); end

  sig { params(args: T.untyped, kwargs: T.untyped).returns(String) }
  def new_super_admin_user_url(*args, **kwargs); end

  # Sigs for route /super_admin/usuarios/:id/edit(.:format)
  sig { params(args: T.untyped, kwargs: T.untyped).returns(String) }
  def edit_super_admin_user_path(*args, **kwargs); end

  sig { params(args: T.untyped, kwargs: T.untyped).returns(String) }
  def edit_super_admin_user_url(*args, **kwargs); end

  # Sigs for route /super_admin/usuarios/:id(.:format)
  sig { params(args: T.untyped, kwargs: T.untyped).returns(String) }
  def super_admin_user_path(*args, **kwargs); end

  sig { params(args: T.untyped, kwargs: T.untyped).returns(String) }
  def super_admin_user_url(*args, **kwargs); end

  # Sigs for route /admin/usuarios(.:format)
  sig { params(args: T.untyped, kwargs: T.untyped).returns(String) }
  def admin_users_path(*args, **kwargs); end

  sig { params(args: T.untyped, kwargs: T.untyped).returns(String) }
  def admin_users_url(*args, **kwargs); end

  # Sigs for route /admin/usuarios/new(.:format)
  sig { params(args: T.untyped, kwargs: T.untyped).returns(String) }
  def new_admin_user_path(*args, **kwargs); end

  sig { params(args: T.untyped, kwargs: T.untyped).returns(String) }
  def new_admin_user_url(*args, **kwargs); end

  # Sigs for route /admin/usuarios/:id(.:format)
  sig { params(args: T.untyped, kwargs: T.untyped).returns(String) }
  def admin_user_path(*args, **kwargs); end

  sig { params(args: T.untyped, kwargs: T.untyped).returns(String) }
  def admin_user_url(*args, **kwargs); end

  # Sigs for route /admin/invitaciones(.:format)
  sig { params(args: T.untyped, kwargs: T.untyped).returns(String) }
  def admin_invitations_path(*args, **kwargs); end

  sig { params(args: T.untyped, kwargs: T.untyped).returns(String) }
  def admin_invitations_url(*args, **kwargs); end

  # Sigs for route /admin/invitaciones/new(.:format)
  sig { params(args: T.untyped, kwargs: T.untyped).returns(String) }
  def new_admin_invitation_path(*args, **kwargs); end

  sig { params(args: T.untyped, kwargs: T.untyped).returns(String) }
  def new_admin_invitation_url(*args, **kwargs); end

  # Sigs for route /admin/select_plan(.:format)
  sig { params(args: T.untyped, kwargs: T.untyped).returns(String) }
  def admin_select_plan_index_path(*args, **kwargs); end

  sig { params(args: T.untyped, kwargs: T.untyped).returns(String) }
  def admin_select_plan_index_url(*args, **kwargs); end

  # Sigs for route /admin/select_plan/new(.:format)
  sig { params(args: T.untyped, kwargs: T.untyped).returns(String) }
  def new_admin_select_plan_path(*args, **kwargs); end

  sig { params(args: T.untyped, kwargs: T.untyped).returns(String) }
  def new_admin_select_plan_url(*args, **kwargs); end
end
