# This is an autogenerated file for dynamic methods in Ektar::Organization
# Please rerun bundle exec rake rails_rbi:models[Ektar::Organization] to regenerate.

# typed: strong
module Ektar::Organization::ActiveRelation_WhereNot
  sig { params(opts: T.untyped, rest: T.untyped).returns(T.self_type) }
  def not(opts, *rest); end
end

module Ektar::Organization::GeneratedAttributeMethods
  sig { returns(ActiveSupport::TimeWithZone) }
  def created_at; end

  sig { params(value: T.any(Date, Time, ActiveSupport::TimeWithZone)).void }
  def created_at=(value); end

  sig { returns(T::Boolean) }
  def created_at?; end

  sig { returns(T.nilable(Integer)) }
  def ektar_plan_id; end

  sig { params(value: T.nilable(T.any(Numeric, ActiveSupport::Duration))).void }
  def ektar_plan_id=(value); end

  sig { returns(T::Boolean) }
  def ektar_plan_id?; end

  sig { returns(T.nilable(T::Boolean)) }
  def enable; end

  sig { params(value: T.nilable(T::Boolean)).void }
  def enable=(value); end

  sig { returns(T::Boolean) }
  def enable?; end

  sig { returns(String) }
  def global_id; end

  sig { params(value: T.any(String, Symbol)).void }
  def global_id=(value); end

  sig { returns(T::Boolean) }
  def global_id?; end

  sig { returns(Integer) }
  def id; end

  sig { params(value: T.any(Numeric, ActiveSupport::Duration)).void }
  def id=(value); end

  sig { returns(T::Boolean) }
  def id?; end

  sig { returns(String) }
  def name; end

  sig { params(value: T.any(String, Symbol)).void }
  def name=(value); end

  sig { returns(T::Boolean) }
  def name?; end

  sig { returns(ActiveSupport::TimeWithZone) }
  def updated_at; end

  sig { params(value: T.any(Date, Time, ActiveSupport::TimeWithZone)).void }
  def updated_at=(value); end

  sig { returns(T::Boolean) }
  def updated_at?; end
end

module Ektar::Organization::GeneratedAssociationMethods
  sig { returns(::Ektar::Invitation::ActiveRecord_Associations_CollectionProxy) }
  def invitations; end

  sig { returns(T::Array[Integer]) }
  def invitation_ids; end

  sig { params(value: T::Enumerable[::Ektar::Invitation]).void }
  def invitations=(value); end

  sig { returns(::Ektar::Membership::ActiveRecord_Associations_CollectionProxy) }
  def memberships; end

  sig { returns(T::Array[Integer]) }
  def membership_ids; end

  sig { params(value: T::Enumerable[::Ektar::Membership]).void }
  def memberships=(value); end

  sig { returns(T.nilable(::Ektar::Plan)) }
  def plan; end

  sig { params(args: T.untyped, block: T.nilable(T.proc.params(object: ::Ektar::Plan).void)).returns(::Ektar::Plan) }
  def build_plan(*args, &block); end

  sig { params(args: T.untyped, block: T.nilable(T.proc.params(object: ::Ektar::Plan).void)).returns(::Ektar::Plan) }
  def create_plan(*args, &block); end

  sig { params(args: T.untyped, block: T.nilable(T.proc.params(object: ::Ektar::Plan).void)).returns(::Ektar::Plan) }
  def create_plan!(*args, &block); end

  sig { params(value: T.nilable(::Ektar::Plan)).void }
  def plan=(value); end

  sig { returns(::Ektar::User::ActiveRecord_Associations_CollectionProxy) }
  def users; end

  sig { returns(T::Array[Integer]) }
  def user_ids; end

  sig { params(value: T::Enumerable[::Ektar::User]).void }
  def users=(value); end
end

module Ektar::Organization::CustomFinderMethods
  sig { params(limit: Integer).returns(T::Array[Ektar::Organization]) }
  def first_n(limit); end

  sig { params(limit: Integer).returns(T::Array[Ektar::Organization]) }
  def last_n(limit); end

  sig { params(args: T::Array[T.any(Integer, String)]).returns(T::Array[Ektar::Organization]) }
  def find_n(*args); end

  sig { params(id: Integer).returns(T.nilable(Ektar::Organization)) }
  def find_by_id(id); end

  sig { params(id: Integer).returns(Ektar::Organization) }
  def find_by_id!(id); end
end

class Ektar::Organization < Ektar::ApplicationRecord
  include Ektar::Organization::GeneratedAttributeMethods
  include Ektar::Organization::GeneratedAssociationMethods
  extend Ektar::Organization::CustomFinderMethods
  extend PgSearch::Model::ClassMethods
  extend Ektar::Organization::QueryMethodsReturningRelation
  RelationType = T.type_alias { T.any(Ektar::Organization::ActiveRecord_Relation, Ektar::Organization::ActiveRecord_Associations_CollectionProxy, Ektar::Organization::ActiveRecord_AssociationRelation) }
end

module Ektar::Organization::QueryMethodsReturningRelation
  sig { returns(Ektar::Organization::ActiveRecord_Relation) }
  def all; end

  sig { params(block: T.nilable(T.proc.void)).returns(Ektar::Organization::ActiveRecord_Relation) }
  def unscoped(&block); end

  sig { params(args: T.untyped).returns(Ektar::Organization::ActiveRecord_Relation) }
  def select(*args); end

  sig { params(args: T.untyped).returns(Ektar::Organization::ActiveRecord_Relation) }
  def reselect(*args); end

  sig { params(args: T.untyped).returns(Ektar::Organization::ActiveRecord_Relation) }
  def order(*args); end

  sig { params(args: T.untyped).returns(Ektar::Organization::ActiveRecord_Relation) }
  def reorder(*args); end

  sig { params(args: T.untyped).returns(Ektar::Organization::ActiveRecord_Relation) }
  def group(*args); end

  sig { params(args: T.untyped).returns(Ektar::Organization::ActiveRecord_Relation) }
  def limit(*args); end

  sig { params(args: T.untyped).returns(Ektar::Organization::ActiveRecord_Relation) }
  def offset(*args); end

  sig { params(args: T.untyped).returns(Ektar::Organization::ActiveRecord_Relation) }
  def joins(*args); end

  sig { params(args: T.untyped).returns(Ektar::Organization::ActiveRecord_Relation) }
  def left_joins(*args); end

  sig { params(args: T.untyped).returns(Ektar::Organization::ActiveRecord_Relation) }
  def left_outer_joins(*args); end

  sig { params(args: T.untyped).returns(Ektar::Organization::ActiveRecord_Relation) }
  def where(*args); end

  sig { params(args: T.untyped).returns(Ektar::Organization::ActiveRecord_Relation) }
  def rewhere(*args); end

  sig { params(args: T.untyped).returns(Ektar::Organization::ActiveRecord_Relation) }
  def preload(*args); end

  sig { params(args: T.untyped).returns(Ektar::Organization::ActiveRecord_Relation) }
  def extract_associated(*args); end

  sig { params(args: T.untyped).returns(Ektar::Organization::ActiveRecord_Relation) }
  def eager_load(*args); end

  sig { params(args: T.untyped).returns(Ektar::Organization::ActiveRecord_Relation) }
  def includes(*args); end

  sig { params(args: T.untyped).returns(Ektar::Organization::ActiveRecord_Relation) }
  def from(*args); end

  sig { params(args: T.untyped).returns(Ektar::Organization::ActiveRecord_Relation) }
  def lock(*args); end

  sig { params(args: T.untyped).returns(Ektar::Organization::ActiveRecord_Relation) }
  def readonly(*args); end

  sig { params(args: T.untyped).returns(Ektar::Organization::ActiveRecord_Relation) }
  def or(*args); end

  sig { params(args: T.untyped).returns(Ektar::Organization::ActiveRecord_Relation) }
  def having(*args); end

  sig { params(args: T.untyped).returns(Ektar::Organization::ActiveRecord_Relation) }
  def create_with(*args); end

  sig { params(args: T.untyped).returns(Ektar::Organization::ActiveRecord_Relation) }
  def distinct(*args); end

  sig { params(args: T.untyped).returns(Ektar::Organization::ActiveRecord_Relation) }
  def references(*args); end

  sig { params(args: T.untyped).returns(Ektar::Organization::ActiveRecord_Relation) }
  def none(*args); end

  sig { params(args: T.untyped).returns(Ektar::Organization::ActiveRecord_Relation) }
  def unscope(*args); end

  sig { params(args: T.untyped).returns(Ektar::Organization::ActiveRecord_Relation) }
  def optimizer_hints(*args); end

  sig { params(args: T.untyped).returns(Ektar::Organization::ActiveRecord_Relation) }
  def merge(*args); end

  sig { params(args: T.untyped).returns(Ektar::Organization::ActiveRecord_Relation) }
  def except(*args); end

  sig { params(args: T.untyped).returns(Ektar::Organization::ActiveRecord_Relation) }
  def only(*args); end

  sig { params(args: T.untyped, block: T.nilable(T.proc.void)).returns(Ektar::Organization::ActiveRecord_Relation) }
  def extending(*args, &block); end

  sig do
    params(
      of: T.nilable(Integer),
      start: T.nilable(Integer),
      finish: T.nilable(Integer),
      load: T.nilable(T::Boolean),
      error_on_ignore: T.nilable(T::Boolean),
      block: T.nilable(T.proc.params(e: Ektar::Organization::ActiveRecord_Relation).void)
    ).returns(ActiveRecord::Batches::BatchEnumerator)
  end
  def in_batches(of: 1000, start: nil, finish: nil, load: false, error_on_ignore: nil, &block); end
end

module Ektar::Organization::QueryMethodsReturningAssociationRelation
  sig { returns(Ektar::Organization::ActiveRecord_AssociationRelation) }
  def all; end

  sig { params(block: T.nilable(T.proc.void)).returns(Ektar::Organization::ActiveRecord_Relation) }
  def unscoped(&block); end

  sig { params(args: T.untyped).returns(Ektar::Organization::ActiveRecord_AssociationRelation) }
  def select(*args); end

  sig { params(args: T.untyped).returns(Ektar::Organization::ActiveRecord_AssociationRelation) }
  def reselect(*args); end

  sig { params(args: T.untyped).returns(Ektar::Organization::ActiveRecord_AssociationRelation) }
  def order(*args); end

  sig { params(args: T.untyped).returns(Ektar::Organization::ActiveRecord_AssociationRelation) }
  def reorder(*args); end

  sig { params(args: T.untyped).returns(Ektar::Organization::ActiveRecord_AssociationRelation) }
  def group(*args); end

  sig { params(args: T.untyped).returns(Ektar::Organization::ActiveRecord_AssociationRelation) }
  def limit(*args); end

  sig { params(args: T.untyped).returns(Ektar::Organization::ActiveRecord_AssociationRelation) }
  def offset(*args); end

  sig { params(args: T.untyped).returns(Ektar::Organization::ActiveRecord_AssociationRelation) }
  def joins(*args); end

  sig { params(args: T.untyped).returns(Ektar::Organization::ActiveRecord_AssociationRelation) }
  def left_joins(*args); end

  sig { params(args: T.untyped).returns(Ektar::Organization::ActiveRecord_AssociationRelation) }
  def left_outer_joins(*args); end

  sig { params(args: T.untyped).returns(Ektar::Organization::ActiveRecord_AssociationRelation) }
  def where(*args); end

  sig { params(args: T.untyped).returns(Ektar::Organization::ActiveRecord_AssociationRelation) }
  def rewhere(*args); end

  sig { params(args: T.untyped).returns(Ektar::Organization::ActiveRecord_AssociationRelation) }
  def preload(*args); end

  sig { params(args: T.untyped).returns(Ektar::Organization::ActiveRecord_AssociationRelation) }
  def extract_associated(*args); end

  sig { params(args: T.untyped).returns(Ektar::Organization::ActiveRecord_AssociationRelation) }
  def eager_load(*args); end

  sig { params(args: T.untyped).returns(Ektar::Organization::ActiveRecord_AssociationRelation) }
  def includes(*args); end

  sig { params(args: T.untyped).returns(Ektar::Organization::ActiveRecord_AssociationRelation) }
  def from(*args); end

  sig { params(args: T.untyped).returns(Ektar::Organization::ActiveRecord_AssociationRelation) }
  def lock(*args); end

  sig { params(args: T.untyped).returns(Ektar::Organization::ActiveRecord_AssociationRelation) }
  def readonly(*args); end

  sig { params(args: T.untyped).returns(Ektar::Organization::ActiveRecord_AssociationRelation) }
  def or(*args); end

  sig { params(args: T.untyped).returns(Ektar::Organization::ActiveRecord_AssociationRelation) }
  def having(*args); end

  sig { params(args: T.untyped).returns(Ektar::Organization::ActiveRecord_AssociationRelation) }
  def create_with(*args); end

  sig { params(args: T.untyped).returns(Ektar::Organization::ActiveRecord_AssociationRelation) }
  def distinct(*args); end

  sig { params(args: T.untyped).returns(Ektar::Organization::ActiveRecord_AssociationRelation) }
  def references(*args); end

  sig { params(args: T.untyped).returns(Ektar::Organization::ActiveRecord_AssociationRelation) }
  def none(*args); end

  sig { params(args: T.untyped).returns(Ektar::Organization::ActiveRecord_AssociationRelation) }
  def unscope(*args); end

  sig { params(args: T.untyped).returns(Ektar::Organization::ActiveRecord_AssociationRelation) }
  def optimizer_hints(*args); end

  sig { params(args: T.untyped).returns(Ektar::Organization::ActiveRecord_AssociationRelation) }
  def merge(*args); end

  sig { params(args: T.untyped).returns(Ektar::Organization::ActiveRecord_AssociationRelation) }
  def except(*args); end

  sig { params(args: T.untyped).returns(Ektar::Organization::ActiveRecord_AssociationRelation) }
  def only(*args); end

  sig { params(args: T.untyped, block: T.nilable(T.proc.void)).returns(Ektar::Organization::ActiveRecord_AssociationRelation) }
  def extending(*args, &block); end

  sig do
    params(
      of: T.nilable(Integer),
      start: T.nilable(Integer),
      finish: T.nilable(Integer),
      load: T.nilable(T::Boolean),
      error_on_ignore: T.nilable(T::Boolean),
      block: T.nilable(T.proc.params(e: Ektar::Organization::ActiveRecord_AssociationRelation).void)
    ).returns(ActiveRecord::Batches::BatchEnumerator)
  end
  def in_batches(of: 1000, start: nil, finish: nil, load: false, error_on_ignore: nil, &block); end
end

class Ektar::Organization::ActiveRecord_Relation < ActiveRecord::Relation
  include Ektar::Organization::ActiveRelation_WhereNot
  include Ektar::Organization::CustomFinderMethods
  include Ektar::Organization::QueryMethodsReturningRelation
  Elem = type_member(fixed: Ektar::Organization)
end

class Ektar::Organization::ActiveRecord_AssociationRelation < ActiveRecord::AssociationRelation
  include Ektar::Organization::ActiveRelation_WhereNot
  include Ektar::Organization::CustomFinderMethods
  include Ektar::Organization::QueryMethodsReturningAssociationRelation
  Elem = type_member(fixed: Ektar::Organization)
end

class Ektar::Organization::ActiveRecord_Associations_CollectionProxy < ActiveRecord::Associations::CollectionProxy
  include Ektar::Organization::CustomFinderMethods
  include Ektar::Organization::QueryMethodsReturningAssociationRelation
  Elem = type_member(fixed: Ektar::Organization)

  sig { params(records: T.any(Ektar::Organization, T::Array[Ektar::Organization])).returns(T.self_type) }
  def <<(*records); end

  sig { params(records: T.any(Ektar::Organization, T::Array[Ektar::Organization])).returns(T.self_type) }
  def append(*records); end

  sig { params(records: T.any(Ektar::Organization, T::Array[Ektar::Organization])).returns(T.self_type) }
  def push(*records); end

  sig { params(records: T.any(Ektar::Organization, T::Array[Ektar::Organization])).returns(T.self_type) }
  def concat(*records); end
end
