# This is an autogenerated file for dynamic methods in Ektar::Plan
# Please rerun bundle exec rake rails_rbi:models[Ektar::Plan] to regenerate.

# typed: strong
module Ektar::Plan::ActiveRelation_WhereNot
  sig { params(opts: T.untyped, rest: T.untyped).returns(T.self_type) }
  def not(opts, *rest); end
end

module Ektar::Plan::GeneratedAttributeMethods
  sig { returns(T::Boolean) }
  def active; end

  sig { params(value: T::Boolean).void }
  def active=(value); end

  sig { returns(T::Boolean) }
  def active?; end

  sig { returns(ActiveSupport::TimeWithZone) }
  def created_at; end

  sig { params(value: T.any(Date, Time, ActiveSupport::TimeWithZone)).void }
  def created_at=(value); end

  sig { returns(T::Boolean) }
  def created_at?; end

  sig { returns(T::Boolean) }
  def free; end

  sig { params(value: T::Boolean).void }
  def free=(value); end

  sig { returns(T::Boolean) }
  def free?; end

  sig { returns(Integer) }
  def id; end

  sig { params(value: T.any(Numeric, ActiveSupport::Duration)).void }
  def id=(value); end

  sig { returns(T::Boolean) }
  def id?; end

  sig { returns(String) }
  def name; end

  sig { params(value: T.any(String, Symbol)).void }
  def name=(value); end

  sig { returns(T::Boolean) }
  def name?; end

  sig { returns(Integer) }
  def price_cents; end

  sig { params(value: T.any(Numeric, ActiveSupport::Duration)).void }
  def price_cents=(value); end

  sig { returns(T::Boolean) }
  def price_cents?; end

  sig { returns(String) }
  def price_currency; end

  sig { params(value: T.any(String, Symbol)).void }
  def price_currency=(value); end

  sig { returns(T::Boolean) }
  def price_currency?; end

  sig { returns(Integer) }
  def trial; end

  sig { params(value: T.any(Numeric, ActiveSupport::Duration)).void }
  def trial=(value); end

  sig { returns(T::Boolean) }
  def trial?; end

  sig { returns(ActiveSupport::TimeWithZone) }
  def updated_at; end

  sig { params(value: T.any(Date, Time, ActiveSupport::TimeWithZone)).void }
  def updated_at=(value); end

  sig { returns(T::Boolean) }
  def updated_at?; end
end

module Ektar::Plan::GeneratedAssociationMethods
  sig { returns(::Ektar::Organization::ActiveRecord_Associations_CollectionProxy) }
  def organizations; end

  sig { returns(T::Array[Integer]) }
  def organization_ids; end

  sig { params(value: T::Enumerable[::Ektar::Organization]).void }
  def organizations=(value); end

  sig { returns(T.nilable(::ActionText::RichText)) }
  def rich_text_description; end

  sig { params(args: T.untyped, block: T.nilable(T.proc.params(object: ::ActionText::RichText).void)).returns(::ActionText::RichText) }
  def build_rich_text_description(*args, &block); end

  sig { params(args: T.untyped, block: T.nilable(T.proc.params(object: ::ActionText::RichText).void)).returns(::ActionText::RichText) }
  def create_rich_text_description(*args, &block); end

  sig { params(args: T.untyped, block: T.nilable(T.proc.params(object: ::ActionText::RichText).void)).returns(::ActionText::RichText) }
  def create_rich_text_description!(*args, &block); end

  sig { params(value: T.nilable(::ActionText::RichText)).void }
  def rich_text_description=(value); end
end

module Ektar::Plan::CustomFinderMethods
  sig { params(limit: Integer).returns(T::Array[Ektar::Plan]) }
  def first_n(limit); end

  sig { params(limit: Integer).returns(T::Array[Ektar::Plan]) }
  def last_n(limit); end

  sig { params(args: T::Array[T.any(Integer, String)]).returns(T::Array[Ektar::Plan]) }
  def find_n(*args); end

  sig { params(id: Integer).returns(T.nilable(Ektar::Plan)) }
  def find_by_id(id); end

  sig { params(id: Integer).returns(Ektar::Plan) }
  def find_by_id!(id); end
end

class Ektar::Plan < Ektar::ApplicationRecord
  include Ektar::Plan::GeneratedAttributeMethods
  include Ektar::Plan::GeneratedAssociationMethods
  extend Ektar::Plan::CustomFinderMethods
  extend PgSearch::Model::ClassMethods
  extend Ektar::Plan::QueryMethodsReturningRelation
  RelationType = T.type_alias { T.any(Ektar::Plan::ActiveRecord_Relation, Ektar::Plan::ActiveRecord_Associations_CollectionProxy, Ektar::Plan::ActiveRecord_AssociationRelation) }

  sig { params(args: T.untyped).returns(Ektar::Plan::ActiveRecord_Relation) }
  def self.with_rich_text_description(*args); end

  sig { params(args: T.untyped).returns(Ektar::Plan::ActiveRecord_Relation) }
  def self.with_rich_text_description_and_embeds(*args); end
end

class Ektar::Plan::ActiveRecord_Relation < ActiveRecord::Relation
  include Ektar::Plan::ActiveRelation_WhereNot
  include Ektar::Plan::CustomFinderMethods
  include Ektar::Plan::QueryMethodsReturningRelation
  Elem = type_member(fixed: Ektar::Plan)

  sig { params(args: T.untyped).returns(Ektar::Plan::ActiveRecord_Relation) }
  def with_rich_text_description(*args); end

  sig { params(args: T.untyped).returns(Ektar::Plan::ActiveRecord_Relation) }
  def with_rich_text_description_and_embeds(*args); end
end

class Ektar::Plan::ActiveRecord_AssociationRelation < ActiveRecord::AssociationRelation
  include Ektar::Plan::ActiveRelation_WhereNot
  include Ektar::Plan::CustomFinderMethods
  include Ektar::Plan::QueryMethodsReturningAssociationRelation
  Elem = type_member(fixed: Ektar::Plan)

  sig { params(args: T.untyped).returns(Ektar::Plan::ActiveRecord_AssociationRelation) }
  def with_rich_text_description(*args); end

  sig { params(args: T.untyped).returns(Ektar::Plan::ActiveRecord_AssociationRelation) }
  def with_rich_text_description_and_embeds(*args); end
end

class Ektar::Plan::ActiveRecord_Associations_CollectionProxy < ActiveRecord::Associations::CollectionProxy
  include Ektar::Plan::CustomFinderMethods
  include Ektar::Plan::QueryMethodsReturningAssociationRelation
  Elem = type_member(fixed: Ektar::Plan)

  sig { params(args: T.untyped).returns(Ektar::Plan::ActiveRecord_AssociationRelation) }
  def with_rich_text_description(*args); end

  sig { params(args: T.untyped).returns(Ektar::Plan::ActiveRecord_AssociationRelation) }
  def with_rich_text_description_and_embeds(*args); end

  sig { params(records: T.any(Ektar::Plan, T::Array[Ektar::Plan])).returns(T.self_type) }
  def <<(*records); end

  sig { params(records: T.any(Ektar::Plan, T::Array[Ektar::Plan])).returns(T.self_type) }
  def append(*records); end

  sig { params(records: T.any(Ektar::Plan, T::Array[Ektar::Plan])).returns(T.self_type) }
  def push(*records); end

  sig { params(records: T.any(Ektar::Plan, T::Array[Ektar::Plan])).returns(T.self_type) }
  def concat(*records); end
end

module Ektar::Plan::QueryMethodsReturningRelation
  sig { returns(Ektar::Plan::ActiveRecord_Relation) }
  def all; end

  sig { params(block: T.nilable(T.proc.void)).returns(Ektar::Plan::ActiveRecord_Relation) }
  def unscoped(&block); end

  sig { params(args: T.untyped).returns(Ektar::Plan::ActiveRecord_Relation) }
  def select(*args); end

  sig { params(args: T.untyped).returns(Ektar::Plan::ActiveRecord_Relation) }
  def reselect(*args); end

  sig { params(args: T.untyped).returns(Ektar::Plan::ActiveRecord_Relation) }
  def order(*args); end

  sig { params(args: T.untyped).returns(Ektar::Plan::ActiveRecord_Relation) }
  def reorder(*args); end

  sig { params(args: T.untyped).returns(Ektar::Plan::ActiveRecord_Relation) }
  def group(*args); end

  sig { params(args: T.untyped).returns(Ektar::Plan::ActiveRecord_Relation) }
  def limit(*args); end

  sig { params(args: T.untyped).returns(Ektar::Plan::ActiveRecord_Relation) }
  def offset(*args); end

  sig { params(args: T.untyped).returns(Ektar::Plan::ActiveRecord_Relation) }
  def joins(*args); end

  sig { params(args: T.untyped).returns(Ektar::Plan::ActiveRecord_Relation) }
  def left_joins(*args); end

  sig { params(args: T.untyped).returns(Ektar::Plan::ActiveRecord_Relation) }
  def left_outer_joins(*args); end

  sig { params(args: T.untyped).returns(Ektar::Plan::ActiveRecord_Relation) }
  def where(*args); end

  sig { params(args: T.untyped).returns(Ektar::Plan::ActiveRecord_Relation) }
  def rewhere(*args); end

  sig { params(args: T.untyped).returns(Ektar::Plan::ActiveRecord_Relation) }
  def preload(*args); end

  sig { params(args: T.untyped).returns(Ektar::Plan::ActiveRecord_Relation) }
  def extract_associated(*args); end

  sig { params(args: T.untyped).returns(Ektar::Plan::ActiveRecord_Relation) }
  def eager_load(*args); end

  sig { params(args: T.untyped).returns(Ektar::Plan::ActiveRecord_Relation) }
  def includes(*args); end

  sig { params(args: T.untyped).returns(Ektar::Plan::ActiveRecord_Relation) }
  def from(*args); end

  sig { params(args: T.untyped).returns(Ektar::Plan::ActiveRecord_Relation) }
  def lock(*args); end

  sig { params(args: T.untyped).returns(Ektar::Plan::ActiveRecord_Relation) }
  def readonly(*args); end

  sig { params(args: T.untyped).returns(Ektar::Plan::ActiveRecord_Relation) }
  def or(*args); end

  sig { params(args: T.untyped).returns(Ektar::Plan::ActiveRecord_Relation) }
  def having(*args); end

  sig { params(args: T.untyped).returns(Ektar::Plan::ActiveRecord_Relation) }
  def create_with(*args); end

  sig { params(args: T.untyped).returns(Ektar::Plan::ActiveRecord_Relation) }
  def distinct(*args); end

  sig { params(args: T.untyped).returns(Ektar::Plan::ActiveRecord_Relation) }
  def references(*args); end

  sig { params(args: T.untyped).returns(Ektar::Plan::ActiveRecord_Relation) }
  def none(*args); end

  sig { params(args: T.untyped).returns(Ektar::Plan::ActiveRecord_Relation) }
  def unscope(*args); end

  sig { params(args: T.untyped).returns(Ektar::Plan::ActiveRecord_Relation) }
  def optimizer_hints(*args); end

  sig { params(args: T.untyped).returns(Ektar::Plan::ActiveRecord_Relation) }
  def merge(*args); end

  sig { params(args: T.untyped).returns(Ektar::Plan::ActiveRecord_Relation) }
  def except(*args); end

  sig { params(args: T.untyped).returns(Ektar::Plan::ActiveRecord_Relation) }
  def only(*args); end

  sig { params(args: T.untyped, block: T.nilable(T.proc.void)).returns(Ektar::Plan::ActiveRecord_Relation) }
  def extending(*args, &block); end

  sig do
    params(
      of: T.nilable(Integer),
      start: T.nilable(Integer),
      finish: T.nilable(Integer),
      load: T.nilable(T::Boolean),
      error_on_ignore: T.nilable(T::Boolean),
      block: T.nilable(T.proc.params(e: Ektar::Plan::ActiveRecord_Relation).void)
    ).returns(ActiveRecord::Batches::BatchEnumerator)
  end
  def in_batches(of: 1000, start: nil, finish: nil, load: false, error_on_ignore: nil, &block); end
end

module Ektar::Plan::QueryMethodsReturningAssociationRelation
  sig { returns(Ektar::Plan::ActiveRecord_AssociationRelation) }
  def all; end

  sig { params(block: T.nilable(T.proc.void)).returns(Ektar::Plan::ActiveRecord_Relation) }
  def unscoped(&block); end

  sig { params(args: T.untyped).returns(Ektar::Plan::ActiveRecord_AssociationRelation) }
  def select(*args); end

  sig { params(args: T.untyped).returns(Ektar::Plan::ActiveRecord_AssociationRelation) }
  def reselect(*args); end

  sig { params(args: T.untyped).returns(Ektar::Plan::ActiveRecord_AssociationRelation) }
  def order(*args); end

  sig { params(args: T.untyped).returns(Ektar::Plan::ActiveRecord_AssociationRelation) }
  def reorder(*args); end

  sig { params(args: T.untyped).returns(Ektar::Plan::ActiveRecord_AssociationRelation) }
  def group(*args); end

  sig { params(args: T.untyped).returns(Ektar::Plan::ActiveRecord_AssociationRelation) }
  def limit(*args); end

  sig { params(args: T.untyped).returns(Ektar::Plan::ActiveRecord_AssociationRelation) }
  def offset(*args); end

  sig { params(args: T.untyped).returns(Ektar::Plan::ActiveRecord_AssociationRelation) }
  def joins(*args); end

  sig { params(args: T.untyped).returns(Ektar::Plan::ActiveRecord_AssociationRelation) }
  def left_joins(*args); end

  sig { params(args: T.untyped).returns(Ektar::Plan::ActiveRecord_AssociationRelation) }
  def left_outer_joins(*args); end

  sig { params(args: T.untyped).returns(Ektar::Plan::ActiveRecord_AssociationRelation) }
  def where(*args); end

  sig { params(args: T.untyped).returns(Ektar::Plan::ActiveRecord_AssociationRelation) }
  def rewhere(*args); end

  sig { params(args: T.untyped).returns(Ektar::Plan::ActiveRecord_AssociationRelation) }
  def preload(*args); end

  sig { params(args: T.untyped).returns(Ektar::Plan::ActiveRecord_AssociationRelation) }
  def extract_associated(*args); end

  sig { params(args: T.untyped).returns(Ektar::Plan::ActiveRecord_AssociationRelation) }
  def eager_load(*args); end

  sig { params(args: T.untyped).returns(Ektar::Plan::ActiveRecord_AssociationRelation) }
  def includes(*args); end

  sig { params(args: T.untyped).returns(Ektar::Plan::ActiveRecord_AssociationRelation) }
  def from(*args); end

  sig { params(args: T.untyped).returns(Ektar::Plan::ActiveRecord_AssociationRelation) }
  def lock(*args); end

  sig { params(args: T.untyped).returns(Ektar::Plan::ActiveRecord_AssociationRelation) }
  def readonly(*args); end

  sig { params(args: T.untyped).returns(Ektar::Plan::ActiveRecord_AssociationRelation) }
  def or(*args); end

  sig { params(args: T.untyped).returns(Ektar::Plan::ActiveRecord_AssociationRelation) }
  def having(*args); end

  sig { params(args: T.untyped).returns(Ektar::Plan::ActiveRecord_AssociationRelation) }
  def create_with(*args); end

  sig { params(args: T.untyped).returns(Ektar::Plan::ActiveRecord_AssociationRelation) }
  def distinct(*args); end

  sig { params(args: T.untyped).returns(Ektar::Plan::ActiveRecord_AssociationRelation) }
  def references(*args); end

  sig { params(args: T.untyped).returns(Ektar::Plan::ActiveRecord_AssociationRelation) }
  def none(*args); end

  sig { params(args: T.untyped).returns(Ektar::Plan::ActiveRecord_AssociationRelation) }
  def unscope(*args); end

  sig { params(args: T.untyped).returns(Ektar::Plan::ActiveRecord_AssociationRelation) }
  def optimizer_hints(*args); end

  sig { params(args: T.untyped).returns(Ektar::Plan::ActiveRecord_AssociationRelation) }
  def merge(*args); end

  sig { params(args: T.untyped).returns(Ektar::Plan::ActiveRecord_AssociationRelation) }
  def except(*args); end

  sig { params(args: T.untyped).returns(Ektar::Plan::ActiveRecord_AssociationRelation) }
  def only(*args); end

  sig { params(args: T.untyped, block: T.nilable(T.proc.void)).returns(Ektar::Plan::ActiveRecord_AssociationRelation) }
  def extending(*args, &block); end

  sig do
    params(
      of: T.nilable(Integer),
      start: T.nilable(Integer),
      finish: T.nilable(Integer),
      load: T.nilable(T::Boolean),
      error_on_ignore: T.nilable(T::Boolean),
      block: T.nilable(T.proc.params(e: Ektar::Plan::ActiveRecord_AssociationRelation).void)
    ).returns(ActiveRecord::Batches::BatchEnumerator)
  end
  def in_batches(of: 1000, start: nil, finish: nil, load: false, error_on_ignore: nil, &block); end
end
