# This is an autogenerated file for dynamic methods in Ektar::User
# Please rerun bundle exec rake rails_rbi:models[Ektar::User] to regenerate.

# typed: strong
module Ektar::User::ActiveRelation_WhereNot
  sig { params(opts: T.untyped, rest: T.untyped).returns(T.self_type) }
  def not(opts, *rest); end
end

module Ektar::User::GeneratedAttributeMethods
  sig { returns(T.nilable(ActiveSupport::TimeWithZone)) }
  def blocked_at; end

  sig { params(value: T.nilable(T.any(Date, Time, ActiveSupport::TimeWithZone))).void }
  def blocked_at=(value); end

  sig { returns(T::Boolean) }
  def blocked_at?; end

  sig { returns(ActiveSupport::TimeWithZone) }
  def created_at; end

  sig { params(value: T.any(Date, Time, ActiveSupport::TimeWithZone)).void }
  def created_at=(value); end

  sig { returns(T::Boolean) }
  def created_at?; end

  sig { returns(T.nilable(Integer)) }
  def ektar_organization_id; end

  sig { params(value: T.nilable(T.any(Numeric, ActiveSupport::Duration))).void }
  def ektar_organization_id=(value); end

  sig { returns(T::Boolean) }
  def ektar_organization_id?; end

  sig { returns(String) }
  def email; end

  sig { params(value: T.any(String, Symbol)).void }
  def email=(value); end

  sig { returns(T::Boolean) }
  def email?; end

  sig { returns(String) }
  def global_id; end

  sig { params(value: T.any(String, Symbol)).void }
  def global_id=(value); end

  sig { returns(T::Boolean) }
  def global_id?; end

  sig { returns(Integer) }
  def id; end

  sig { params(value: T.any(Numeric, ActiveSupport::Duration)).void }
  def id=(value); end

  sig { returns(T::Boolean) }
  def id?; end

  sig { returns(T.nilable(ActiveSupport::TimeWithZone)) }
  def last_activity_at; end

  sig { params(value: T.nilable(T.any(Date, Time, ActiveSupport::TimeWithZone))).void }
  def last_activity_at=(value); end

  sig { returns(T::Boolean) }
  def last_activity_at?; end

  sig { returns(T.nilable(String)) }
  def last_ip; end

  sig { params(value: T.nilable(T.any(String, Symbol))).void }
  def last_ip=(value); end

  sig { returns(T::Boolean) }
  def last_ip?; end

  sig { returns(String) }
  def password_digest; end

  sig { params(value: T.any(String, Symbol)).void }
  def password_digest=(value); end

  sig { returns(T::Boolean) }
  def password_digest?; end

  sig { returns(T.nilable(String)) }
  def recovery_password_digest; end

  sig { params(value: T.nilable(T.any(String, Symbol))).void }
  def recovery_password_digest=(value); end

  sig { returns(T::Boolean) }
  def recovery_password_digest?; end

  sig { returns(T.nilable(String)) }
  def reset_password_token; end

  sig { params(value: T.nilable(T.any(String, Symbol))).void }
  def reset_password_token=(value); end

  sig { returns(T::Boolean) }
  def reset_password_token?; end

  sig { returns(T.nilable(T::Boolean)) }
  def super_admin; end

  sig { params(value: T.nilable(T::Boolean)).void }
  def super_admin=(value); end

  sig { returns(T::Boolean) }
  def super_admin?; end

  sig { returns(ActiveSupport::TimeWithZone) }
  def updated_at; end

  sig { params(value: T.any(Date, Time, ActiveSupport::TimeWithZone)).void }
  def updated_at=(value); end

  sig { returns(T::Boolean) }
  def updated_at?; end
end

module Ektar::User::GeneratedAssociationMethods
  sig { returns(::Ektar::Membership::ActiveRecord_Associations_CollectionProxy) }
  def memberships; end

  sig { returns(T::Array[Integer]) }
  def membership_ids; end

  sig { params(value: T::Enumerable[::Ektar::Membership]).void }
  def memberships=(value); end

  sig { returns(::Ektar::Organization::ActiveRecord_Associations_CollectionProxy) }
  def organizations; end

  sig { returns(T::Array[Integer]) }
  def organization_ids; end

  sig { params(value: T::Enumerable[::Ektar::Organization]).void }
  def organizations=(value); end

  sig { returns(::Ektar::UsedPassword::ActiveRecord_Associations_CollectionProxy) }
  def used_passwords; end

  sig { returns(T::Array[Integer]) }
  def used_password_ids; end

  sig { params(value: T::Enumerable[::Ektar::UsedPassword]).void }
  def used_passwords=(value); end
end

module Ektar::User::CustomFinderMethods
  sig { params(limit: Integer).returns(T::Array[Ektar::User]) }
  def first_n(limit); end

  sig { params(limit: Integer).returns(T::Array[Ektar::User]) }
  def last_n(limit); end

  sig { params(args: T::Array[T.any(Integer, String)]).returns(T::Array[Ektar::User]) }
  def find_n(*args); end

  sig { params(id: Integer).returns(T.nilable(Ektar::User)) }
  def find_by_id(id); end

  sig { params(id: Integer).returns(Ektar::User) }
  def find_by_id!(id); end
end

class Ektar::User < Ektar::ApplicationRecord
  include Ektar::User::GeneratedAttributeMethods
  include Ektar::User::GeneratedAssociationMethods
  extend Ektar::User::CustomFinderMethods
  extend PgSearch::Model::ClassMethods
  extend Ektar::User::QueryMethodsReturningRelation
  RelationType = T.type_alias { T.any(Ektar::User::ActiveRecord_Relation, Ektar::User::ActiveRecord_Associations_CollectionProxy, Ektar::User::ActiveRecord_AssociationRelation) }

  sig { params(args: T.untyped).returns(Ektar::User::ActiveRecord_Relation) }
  def self.super_admins(*args); end
end

class Ektar::User::ActiveRecord_Relation < ActiveRecord::Relation
  include Ektar::User::ActiveRelation_WhereNot
  include Ektar::User::CustomFinderMethods
  include Ektar::User::QueryMethodsReturningRelation
  Elem = type_member(fixed: Ektar::User)

  sig { params(args: T.untyped).returns(Ektar::User::ActiveRecord_Relation) }
  def super_admins(*args); end
end

class Ektar::User::ActiveRecord_AssociationRelation < ActiveRecord::AssociationRelation
  include Ektar::User::ActiveRelation_WhereNot
  include Ektar::User::CustomFinderMethods
  include Ektar::User::QueryMethodsReturningAssociationRelation
  Elem = type_member(fixed: Ektar::User)

  sig { params(args: T.untyped).returns(Ektar::User::ActiveRecord_AssociationRelation) }
  def super_admins(*args); end
end

class Ektar::User::ActiveRecord_Associations_CollectionProxy < ActiveRecord::Associations::CollectionProxy
  include Ektar::User::CustomFinderMethods
  include Ektar::User::QueryMethodsReturningAssociationRelation
  Elem = type_member(fixed: Ektar::User)

  sig { params(args: T.untyped).returns(Ektar::User::ActiveRecord_AssociationRelation) }
  def super_admins(*args); end

  sig { params(records: T.any(Ektar::User, T::Array[Ektar::User])).returns(T.self_type) }
  def <<(*records); end

  sig { params(records: T.any(Ektar::User, T::Array[Ektar::User])).returns(T.self_type) }
  def append(*records); end

  sig { params(records: T.any(Ektar::User, T::Array[Ektar::User])).returns(T.self_type) }
  def push(*records); end

  sig { params(records: T.any(Ektar::User, T::Array[Ektar::User])).returns(T.self_type) }
  def concat(*records); end
end

module Ektar::User::QueryMethodsReturningRelation
  sig { returns(Ektar::User::ActiveRecord_Relation) }
  def all; end

  sig { params(block: T.nilable(T.proc.void)).returns(Ektar::User::ActiveRecord_Relation) }
  def unscoped(&block); end

  sig { params(args: T.untyped).returns(Ektar::User::ActiveRecord_Relation) }
  def select(*args); end

  sig { params(args: T.untyped).returns(Ektar::User::ActiveRecord_Relation) }
  def reselect(*args); end

  sig { params(args: T.untyped).returns(Ektar::User::ActiveRecord_Relation) }
  def order(*args); end

  sig { params(args: T.untyped).returns(Ektar::User::ActiveRecord_Relation) }
  def reorder(*args); end

  sig { params(args: T.untyped).returns(Ektar::User::ActiveRecord_Relation) }
  def group(*args); end

  sig { params(args: T.untyped).returns(Ektar::User::ActiveRecord_Relation) }
  def limit(*args); end

  sig { params(args: T.untyped).returns(Ektar::User::ActiveRecord_Relation) }
  def offset(*args); end

  sig { params(args: T.untyped).returns(Ektar::User::ActiveRecord_Relation) }
  def joins(*args); end

  sig { params(args: T.untyped).returns(Ektar::User::ActiveRecord_Relation) }
  def left_joins(*args); end

  sig { params(args: T.untyped).returns(Ektar::User::ActiveRecord_Relation) }
  def left_outer_joins(*args); end

  sig { params(args: T.untyped).returns(Ektar::User::ActiveRecord_Relation) }
  def where(*args); end

  sig { params(args: T.untyped).returns(Ektar::User::ActiveRecord_Relation) }
  def rewhere(*args); end

  sig { params(args: T.untyped).returns(Ektar::User::ActiveRecord_Relation) }
  def preload(*args); end

  sig { params(args: T.untyped).returns(Ektar::User::ActiveRecord_Relation) }
  def extract_associated(*args); end

  sig { params(args: T.untyped).returns(Ektar::User::ActiveRecord_Relation) }
  def eager_load(*args); end

  sig { params(args: T.untyped).returns(Ektar::User::ActiveRecord_Relation) }
  def includes(*args); end

  sig { params(args: T.untyped).returns(Ektar::User::ActiveRecord_Relation) }
  def from(*args); end

  sig { params(args: T.untyped).returns(Ektar::User::ActiveRecord_Relation) }
  def lock(*args); end

  sig { params(args: T.untyped).returns(Ektar::User::ActiveRecord_Relation) }
  def readonly(*args); end

  sig { params(args: T.untyped).returns(Ektar::User::ActiveRecord_Relation) }
  def or(*args); end

  sig { params(args: T.untyped).returns(Ektar::User::ActiveRecord_Relation) }
  def having(*args); end

  sig { params(args: T.untyped).returns(Ektar::User::ActiveRecord_Relation) }
  def create_with(*args); end

  sig { params(args: T.untyped).returns(Ektar::User::ActiveRecord_Relation) }
  def distinct(*args); end

  sig { params(args: T.untyped).returns(Ektar::User::ActiveRecord_Relation) }
  def references(*args); end

  sig { params(args: T.untyped).returns(Ektar::User::ActiveRecord_Relation) }
  def none(*args); end

  sig { params(args: T.untyped).returns(Ektar::User::ActiveRecord_Relation) }
  def unscope(*args); end

  sig { params(args: T.untyped).returns(Ektar::User::ActiveRecord_Relation) }
  def optimizer_hints(*args); end

  sig { params(args: T.untyped).returns(Ektar::User::ActiveRecord_Relation) }
  def merge(*args); end

  sig { params(args: T.untyped).returns(Ektar::User::ActiveRecord_Relation) }
  def except(*args); end

  sig { params(args: T.untyped).returns(Ektar::User::ActiveRecord_Relation) }
  def only(*args); end

  sig { params(args: T.untyped, block: T.nilable(T.proc.void)).returns(Ektar::User::ActiveRecord_Relation) }
  def extending(*args, &block); end

  sig do
    params(
      of: T.nilable(Integer),
      start: T.nilable(Integer),
      finish: T.nilable(Integer),
      load: T.nilable(T::Boolean),
      error_on_ignore: T.nilable(T::Boolean),
      block: T.nilable(T.proc.params(e: Ektar::User::ActiveRecord_Relation).void)
    ).returns(ActiveRecord::Batches::BatchEnumerator)
  end
  def in_batches(of: 1000, start: nil, finish: nil, load: false, error_on_ignore: nil, &block); end
end

module Ektar::User::QueryMethodsReturningAssociationRelation
  sig { returns(Ektar::User::ActiveRecord_AssociationRelation) }
  def all; end

  sig { params(block: T.nilable(T.proc.void)).returns(Ektar::User::ActiveRecord_Relation) }
  def unscoped(&block); end

  sig { params(args: T.untyped).returns(Ektar::User::ActiveRecord_AssociationRelation) }
  def select(*args); end

  sig { params(args: T.untyped).returns(Ektar::User::ActiveRecord_AssociationRelation) }
  def reselect(*args); end

  sig { params(args: T.untyped).returns(Ektar::User::ActiveRecord_AssociationRelation) }
  def order(*args); end

  sig { params(args: T.untyped).returns(Ektar::User::ActiveRecord_AssociationRelation) }
  def reorder(*args); end

  sig { params(args: T.untyped).returns(Ektar::User::ActiveRecord_AssociationRelation) }
  def group(*args); end

  sig { params(args: T.untyped).returns(Ektar::User::ActiveRecord_AssociationRelation) }
  def limit(*args); end

  sig { params(args: T.untyped).returns(Ektar::User::ActiveRecord_AssociationRelation) }
  def offset(*args); end

  sig { params(args: T.untyped).returns(Ektar::User::ActiveRecord_AssociationRelation) }
  def joins(*args); end

  sig { params(args: T.untyped).returns(Ektar::User::ActiveRecord_AssociationRelation) }
  def left_joins(*args); end

  sig { params(args: T.untyped).returns(Ektar::User::ActiveRecord_AssociationRelation) }
  def left_outer_joins(*args); end

  sig { params(args: T.untyped).returns(Ektar::User::ActiveRecord_AssociationRelation) }
  def where(*args); end

  sig { params(args: T.untyped).returns(Ektar::User::ActiveRecord_AssociationRelation) }
  def rewhere(*args); end

  sig { params(args: T.untyped).returns(Ektar::User::ActiveRecord_AssociationRelation) }
  def preload(*args); end

  sig { params(args: T.untyped).returns(Ektar::User::ActiveRecord_AssociationRelation) }
  def extract_associated(*args); end

  sig { params(args: T.untyped).returns(Ektar::User::ActiveRecord_AssociationRelation) }
  def eager_load(*args); end

  sig { params(args: T.untyped).returns(Ektar::User::ActiveRecord_AssociationRelation) }
  def includes(*args); end

  sig { params(args: T.untyped).returns(Ektar::User::ActiveRecord_AssociationRelation) }
  def from(*args); end

  sig { params(args: T.untyped).returns(Ektar::User::ActiveRecord_AssociationRelation) }
  def lock(*args); end

  sig { params(args: T.untyped).returns(Ektar::User::ActiveRecord_AssociationRelation) }
  def readonly(*args); end

  sig { params(args: T.untyped).returns(Ektar::User::ActiveRecord_AssociationRelation) }
  def or(*args); end

  sig { params(args: T.untyped).returns(Ektar::User::ActiveRecord_AssociationRelation) }
  def having(*args); end

  sig { params(args: T.untyped).returns(Ektar::User::ActiveRecord_AssociationRelation) }
  def create_with(*args); end

  sig { params(args: T.untyped).returns(Ektar::User::ActiveRecord_AssociationRelation) }
  def distinct(*args); end

  sig { params(args: T.untyped).returns(Ektar::User::ActiveRecord_AssociationRelation) }
  def references(*args); end

  sig { params(args: T.untyped).returns(Ektar::User::ActiveRecord_AssociationRelation) }
  def none(*args); end

  sig { params(args: T.untyped).returns(Ektar::User::ActiveRecord_AssociationRelation) }
  def unscope(*args); end

  sig { params(args: T.untyped).returns(Ektar::User::ActiveRecord_AssociationRelation) }
  def optimizer_hints(*args); end

  sig { params(args: T.untyped).returns(Ektar::User::ActiveRecord_AssociationRelation) }
  def merge(*args); end

  sig { params(args: T.untyped).returns(Ektar::User::ActiveRecord_AssociationRelation) }
  def except(*args); end

  sig { params(args: T.untyped).returns(Ektar::User::ActiveRecord_AssociationRelation) }
  def only(*args); end

  sig { params(args: T.untyped, block: T.nilable(T.proc.void)).returns(Ektar::User::ActiveRecord_AssociationRelation) }
  def extending(*args, &block); end

  sig do
    params(
      of: T.nilable(Integer),
      start: T.nilable(Integer),
      finish: T.nilable(Integer),
      load: T.nilable(T::Boolean),
      error_on_ignore: T.nilable(T::Boolean),
      block: T.nilable(T.proc.params(e: Ektar::User::ActiveRecord_AssociationRelation).void)
    ).returns(ActiveRecord::Batches::BatchEnumerator)
  end
  def in_batches(of: 1000, start: nil, finish: nil, load: false, error_on_ignore: nil, &block); end
end
